version: '3.7'

services:
  app:
    restart: always
    container_name: openai
    build: .
    ports:
      - "3000:3000"
    networks: 
      - data
    volumes:
      - ./data:/data       

networks:
  data:
    driver: bridge