version: '3.7'

services:
  app:
    restart: always
    container_name: chat-ai
    build: .
    ports:
      - "3000:3000"
    networks: 
      - bridge
    volumes:
      - ./data:/data       

networks:
  bridge:
    driver: bridge