version: '3.7'

services:
  api:
    restart: always
    container_name: chat-ai
    build: .
    ports:
      - "8282:3000"
    networks: 
      - bridge
    volumes:
      - chat_data:/var/www/chat         

networks:
  bridge:
    driver: bridge

volumes:
  chat_data: