version: '3.7'

services:
  chat-ai:
    restart: always
    container_name: chat-ai
    build: .
    ports:
      - "3000:3000"
    networks: 
      - bridge
    volumes:
      - chat-ai:/var/www/chat         

networks:
  bridge:
    driver: bridge

volumes:
  chat-ai: